### ISSUE TITLE
Missing +1 in tm_mon ?

### ISSUE THREAD

**Issue by colinleroy** [bobbimanners/ProDOS-Utils#20]
https://github.com/bobbimanners/ProDOS-Utils/blob/373eab52c988a3862d34d994d6b2aba2e8c92b62/veserver.py#L67

**Comment by bobbimanners** [comment]
Hi Colin - sorry this got lost in my inbox and I am only now looking at it!!

I don't recall the details since it has been ages since I wrote this code.  I expect you are right about the +1.  Before I just blindly commit a change, I am curious what made you think it was off by one?  Assuming it differs the output from other tools.

**Comment by colinleroy** [comment]
Well I should have read all the docs, my PR is wrong and your code is correct. Python's tm_mon is [1..12], ProDOS 2.4 too, and ProDOS 2.5 is [2..13] so your code is right :-)

**Comment by bobbimanners** [comment]
Turns out ProDOS 2.5 has a weird format for the month of the year and the Veserver code appears to be correct according the the ProDOS 2.5 docs.
